### ISSUE TITLE
split README into multiple Wiki-Sites?

### ISSUE THREAD

**Issue by Thor77** [ldidry/lutim#64]
I think the huge README.md should be splitted into multiple smaller (Github)Wiki-Sites (one for each section?) and the README should only contain basic information and a link to the wiki.
What do you think?

**Comment by ldidry** [comment]
I already thought of move README parts in a wiki ;-) Yes, it's a good idea.

I plan to create an API page in Lutim like I did with [Lstu](https://lstu.fr/api). The Nginx part will go in a file in `utilities` directory. After that, if the README is still huge, yes I will create a wiki. But on <https://git.framasoft.org/luc/lutim> since it's now the official repository (github hosts just a mirror of that repo).

**Comment by Thor77** [comment]
Whats about [aglio](https://github.com/danielgtaylor/aglio) for the API it looks really cool and has a lot of customization-options!

Just created an account on framasoftgit, will create future issues and pull requests there.

**Comment by ldidry** [comment]
> Whats about aglio for the API? I think it looks quite good.

Yes, I know it, I use it for [Erco](https://git.framasoft.org/luc/erco) [API](https://erco.xyz/demo/api/index.html).

The downside is that I can't use .po files to translate the API (the API page of Lstu is internationalized).

> Just created an account on framasoftgit, will create future issues and pull requests there.

You could have use your github account on it. Or maybe you did;-)

**Comment by ldidry** [comment]
Split in a wiki : https://git.framasoft.org/luc/lutim/wikis/home
