### ISSUE TITLE
Improvement - systemd unit file for lutim

### ISSUE THREAD

**Issue by mirtouf** [ldidry/lutim#65]
Hi,

as I did not want to guess why the init script launch failed on my Debian Jessie, I wrote a simple systemd unit file for Lutim:
```
[Unit]
Description=Lutim
Documentation=https://github.com/ldidry/lutim

[Service]
Type=forking
WorkingDirectory=<your working dir>
ExecStart=/usr/bin/carton exec hypnotoad script/lutim

[Install]
WantedBy=multi-user.target
```
It works but I still wonder:
- is it still interesting to set the WorkingDirectory through a call to /etc/default/lutim ($LDIR) rather than modifying the unit file ?
- the hypnotoad pid file is correctly created but is it better to add a PIDFile variable in systemd unit ?

cheers !

**Comment by ldidry** [comment]
> is it still interesting to set the WorkingDirectory through a call to /etc/default/lutim ($LDIR) rather than modifying the unit file ?

Yes, it is, since the user would only have to change a configuration file, and not a .service file. It would avoid the need of `systemctl daemon-reload` if the user choose to change the lutim directory.

Unfortunately, I tried to use a `/etc/default/lutim` file with Lutim, but failed. I had success only by changing the WorkingDirectory in lutim.service.

That's not really important, I think. It would be better, but I think we can live with editing lutim.service.

> the hypnotoad pid file is correctly created but is it better to add a PIDFile variable in systemd unit ?

Yes, otherwise I'm not sure that systemd will be able to properly stop Lutim.

Best solution (to me): 

```
Type=simple
ExecStart=/usr/bin/carton exec hypnotoad -f script/lutim
ExecReload=/usr/bin/carton exec hypnotoad script/lutim
ExecStop=/usr/bin/carton exec hypnotoad -s script/lutim
Restart=always
```

Hint: add 
```
Requires=network.target
After=network.target
```
in `[Unit]`

**********
I worked on a systemd service file for [Lstu](https://git.framasoft.org/luc/lstu) (Lstu is a URL shortening software older than Lutim. The code of Lutim is quite similar to Lstu's. When I experiment things, I test on Lstu before). I began with .service file similar to yours (<https://git.framasoft.org/luc/lstu/blob/f2a977fa806ae0c1fd686acda07007dff4136980/utilities/lstu.service>), then I tried the [Mojolicious recommendations](https://github.com/kraih/mojo/wiki/Integrating-hypnotoad-with-systemd-and-rsyslog) but it's not optimal. <https://git.framasoft.org/luc/lstu/blob/master/utilities/lstu.service> shows itself as working with `systemctl status` even if it failed.

I planned to include a .service file in Lutim repo next week :wink: 

********
Last thing: I'm moving the developpment of Lutim at <https://git.framasoft.org/luc/lutim>. Github is now just a mirror. So it would be good to change the `Documentation` URL :smiley:

**Comment by ldidry** [comment]
Working systemd service file added in 1f0aa046d42785b0c57287e7b56f9631711f6146 and improved in bb9fae43e24f0cfe1a6e86fec11e64760e2dbe55
